### PR TITLE
added gradlew auto builder

### PR DESCRIPTION
**Pull request by flufferyomada**
idk lol

### CODE REVIEW

**Comment by flufferyomada** [comment]
the dub counter didnt work and i dont want to make it, call me lazy but effort im not doing

**Comment by flufferyomada** [comment]
done proudly on my Motorola G Play 2021!

**Comment by Tarkan-Zarrouk** [comment]
Couldn't you just delete your fork, create a new fork then add the git actions and then make a pr so it reduces the amount of commits lol

**Comment by flufferyomada** [comment]
Of course not! I must be the most annoying person with prs!

**Comment by srgantmoomoo** [comment]
:yawning_face:

**Pull request closed without merging**
