### PR TITLE
Tried making a dub chest counter

### PR DESCRIPTION
**Pull request by flufferyomada**
this may not work, i did not have minecraft sdk and got TileEntityChest from someone when i was making this quality of life hud module

### CODE REVIEW

**Comment by srgantmoomoo** [comment]
what does "this may not work" mean lmao. can u test it??? i'll test it when i get a chance of course but i think u should know whether it works or not before making it a pr.

**Comment by DrFluffery** [comment]
yea i'll test it, i've just been really busy but i mean i can always update the pr

**Comment by srgantmoomoo** [comment]
Yes sorry i forgor ab this… i also been very busy lol. I will make sure to test it myself whenever i get the chance.

**Comment by DrFluffery** [comment]
ill probs do it tmr or saturday

**Comment by srgantmoomoo** [comment]
there are a bunch of errors in ur code... i'm guessing this wasn't even written in an ide?? lmfao!!

**Comment by Tarkan-Zarrouk** [comment]
how dare you exclaim "lmfao!!", notepad is the best ide! :(

**Comment by flufferyomada** [comment]
I didnt use notepad i used nano because eclipse and intellij weren't opening

**Comment by TwoThreeTwo** [comment]
Gay

**Comment by srgantmoomoo** [comment]
Ok I’m closing it cause it don’t work. If you wanna make a new one with changes, u can.

**Comment by Tarkan-Zarrouk** [comment]
sob!

**Pull request closed without merging**
